---
driver_plugin: vagrant

provisioner:
  product_name: chef
  product_version: 12.22.1

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]

  - name: ubuntu-16.04
    run_list:
    - recipe[apt]

  - name: centos-6
    run_list:
    - recipe[apt]

  - name: centos-7
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
    - recipe[crowd]
    attributes:
      crowd:
        version: 3.0.1
      apt:
        compile_time_update: true
      postgresql:
        password:
          postgres: thisisnotapassword