---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]

  - name: ubuntu-16.04
    run_list:
    - recipe[apt]

  - name: centos-6.5
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
    - recipe[crowd]
    attributes:
      crowd:
        version: 3.0.1
      apt:
        compile_time_update: true
