AllCops:
  Include:
  - Berksfile
  - Gemfile
  - Guardfile
  - Rakefile
  Exclude:
  - test/**/*
  - spec/**/*
  - vendor/**/*
  - ruby/**/*
  - Vagrantfile
  TargetRubyVersion: 2.4

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
  Exclude:
  - "libraries/crowd.rb"
Style/NumericLiteralPrefix:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
  - "libraries/crowd.rb"
Metrics/AbcSize:
  Exclude:
  - "libraries/crowd.rb"
Metrics/CyclomaticComplexity:
  Exclude:
  - "libraries/crowd.rb"
Metrics/PerceivedComplexity:
  Exclude:
  - "libraries/crowd.rb"