language: ruby
cache: bundler
bundler_args: --without integration
rvm:
  - 2.2.3
#bundler_args: --without development
before_script:
  - bundle exec berks install
script:
  # - bundle exec knife cookbook test -a -o .
  - bundle exec rake
notifications:
  email: false